### ISSUE TITLE
Clicking on the WordPress logo on the top right screen of an update CPT throws an error

### ISSUE THREAD

**Issue by harishankerr** [WordPress/revisions-extended#82] opened 2021-02-25 11:00 UTC
### Summary

When one creates an update that gets correctly scheduled, and then tries to go back to the list of updates - an error message: `Sorry, you are not allowed to list revisions this way.` is thrown. 

### Steps to replicate

1. Edit a new (or existing post) to add some updates, and schedule it to a future date. 
2. Open the update CPT (either by clicking `Continue editing your update` from the prompt or by visiting **Posts > Updates**). The error can also be replicated by attempting to edit an existing revision CPT from **Posts > Updates**.
3. Once you are on the page, click on the WordPress logo on the top left corner of the Block editor page.
4. You will now see an error message titled; `Sorry, you are not allowed to list revisions this way.`The user is being redirected to: `/wp-admin/edit.php?post_type=revision` instead of `/wp-admin/edit.php?page=post-updates`.

Here's a screencast depicting the issue:

![https://d.pr/i/M4UFgP](https://d.pr/i/M4UFgP+) 
Full Size: https://d.pr/i/M4UFgP

### Notes

* The issue seems to be random. For some posts or in some cases (especially when the update is accessed directly from **Posts > Updates**), clicking on the WordPress logo seems to redirect correctly to: `/wp-admin/edit.php?page=post-updates`. However, this happened probably 2-3 times out of the 10-15 attempts I tested this issue with. In all my other attempts, I kept running into this error. Every time I went to the revision page directly from the post editor, I encountered this error. 
* A band-aid fix would be to fix the redirect URL to: `/wp-admin/edit.php?page=post-updates`. I think it's happening because it's trying to redirect to the post edit page of the revision CPT.

**Comment by StevenDufresne** [comment] 2021-02-25 23:13
@coreymckrill When was the plugin updated last on the test site?

**Comment by coreymckrill** [comment] 2021-02-25 23:31
Two days ago, so the fix should already be deployed. But I can reproduce this bug 😕 

There are some unrelated changes that haven't been deployed yet, so I'll do that and see if anything changes.

**Comment by coreymckrill** [comment] 2021-02-25 23:51
@StevenDufresne It's weird, this only happens on the Make test site. If I go to the Edit Update screen, the logo URL is wrong. But while on that screen, if I clear my browser cache and do a hard refresh, it comes back with the correct URL. Maybe there's a race condition?

**Comment by StevenDufresne** [comment] 2021-02-26 00:28
Yeah, the code is open to race conditions. I think the change may need to be on Gutenberg's side. 

It appears like that button is continually re-rendering. Not certain it needs to.

**Comment by StevenDufresne** [comment] 2021-03-09 01:11
Since #91 was merged, I think we can close this until it resurfaces.

**Closed as completed by StevenDufresne** 2021-03-09 01:11 UTC
Labels: bug
